name: Test

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2

      - name: Perform quality checks
        run: |
          yarn install
          yarn format:check
          yarn lint:check
          yarn build
          # yarn test
